"""
This type stub file was generated by pyright.
"""

import matplotlib
from packaging import version
from ._version import __version__

CMAPSFILE_DIR = ...
USER_CMAPFILE_DIR = ...
if version.parse(matplotlib.__version__) < version.parse('3.2.0'):
    ...
if version.parse(matplotlib.__version__) >= version.parse('3.7'):
    get_cmap = ...
    register_cmap = ...
else:
    get_cmap = ...
    register_cmap = ...
class Cmaps:
    """colormaps"""
    def __init__(self) -> None:
        ...
    
    @property
    def N3gauss(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def N3gauss_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def N3saw(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def N3saw_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BkBlAqGrYeOrReViWh200(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BkBlAqGrYeOrReViWh200_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlAqGrWh2YeOrReVi22(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlAqGrWh2YeOrReVi22_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlAqGrYeOrRe(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlAqGrYeOrRe_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlAqGrYeOrReVi200(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlAqGrYeOrReVi200_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlGrYeOrReVi200(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlGrYeOrReVi200_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlRe(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlRe_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlWhRe(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlWhRe_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueDarkOrange18(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueDarkOrange18_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueDarkRed18(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueDarkRed18_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueGreen14(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueGreen14_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueRed(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueRed_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueRedGray(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueRedGray_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueWhiteOrangeRed(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueWhiteOrangeRed_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueYellowRed(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BlueYellowRed_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BrownBlue12(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def BrownBlue12_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def CBR_coldhot(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def CBR_coldhot_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def CBR_drywet(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def CBR_drywet_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def CBR_set3(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def CBR_set3_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def CBR_wet(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def CBR_wet_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def Cat12(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def Cat12_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GHRSST_anomaly(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GHRSST_anomaly_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_cool(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_cool_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_copper(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_copper_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_drywet(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_drywet_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_gebco(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_gebco_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_globe(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_globe_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_gray(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_gray_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_haxby(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_haxby_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_hot(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_hot_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_jet(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_jet_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_nighttime(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_nighttime_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_no_green(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_no_green_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_ocean(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_ocean_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_paired(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_paired_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_panoply(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_panoply_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_polar(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_polar_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_red2green(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_red2green_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_relief(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_relief_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_relief_oceanonly(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_relief_oceanonly_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_seis(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_seis_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_split(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_split_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_topo(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_topo_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_wysiwyg(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_wysiwyg_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_wysiwygcont(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GMT_wysiwygcont_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GSFC_landsat_udf_density(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GSFC_landsat_udf_density_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GrayWhiteGray(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GrayWhiteGray_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GreenMagenta16(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GreenMagenta16_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GreenYellow(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def GreenYellow_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Accent(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Accent_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Blues(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Blues_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_BrBG(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_BrBG_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_BuGn(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_BuGn_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_BuPu(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_BuPu_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Dark2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Dark2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_GnBu(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_GnBu_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Greens(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Greens_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Greys(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Greys_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_OrRd(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_OrRd_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Oranges(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Oranges_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PRGn(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PRGn_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Paired(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Paired_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Pastel1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Pastel1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Pastel2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Pastel2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PiYG(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PiYG_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PuBu(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PuBu_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PuBuGn(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PuBuGn_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PuOr(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PuOr_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PuRd(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_PuRd_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Purples(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Purples_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdBu(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdBu_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdGy(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdGy_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdPu(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdPu_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdYlBu(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdYlBu_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdYlGn(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_RdYlGn_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Reds(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Reds_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Set1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Set1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Set2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Set2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Set3(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Set3_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Spectral(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_Spectral_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_StepSeq(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_StepSeq_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_YlGn(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_YlGn_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_YlGnBu(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_YlGnBu_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_YlOrBr(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_YlOrBr_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_YlOrRd(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_YlOrRd_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_afmhot(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_afmhot_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_autumn(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_autumn_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_bone(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_bone_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_brg(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_brg_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_bwr(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_bwr_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_cool(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_cool_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_coolwarm(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_coolwarm_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_copper(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_copper_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_cubehelix(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_cubehelix_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_flag(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_flag_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_earth(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_earth_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_gray(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_gray_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_heat(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_heat_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_ncar(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_ncar_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_rainbow(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_rainbow_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_stern(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_stern_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_yarg(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gist_yarg_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gnuplot(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gnuplot_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gnuplot2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_gnuplot2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_hot(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_hot_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_hsv(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_hsv_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_jet(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_jet_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_ocean(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_ocean_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_pink(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_pink_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_prism(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_prism_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_rainbow(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_rainbow_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_s3pcpn(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_s3pcpn_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_s3pcpn_l(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_s3pcpn_l_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_seismic(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_seismic_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_spring(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_spring_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_sstanom(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_sstanom_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_summer(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_summer_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_terrain(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_terrain_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_viridis(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_viridis_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_winter(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def MPL_winter_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_banded(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_banded_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_blu_red(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_blu_red_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_blue_red(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_blue_red_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_bright(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_bright_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_gebco(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_gebco_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_jaisnd(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_jaisnd_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_jet(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_jet_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_manga(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_manga_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_rainbow2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_rainbow2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_roullet(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NCV_roullet_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NEO_div_vegetation_a(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NEO_div_vegetation_a_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NEO_div_vegetation_b(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NEO_div_vegetation_b_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NEO_div_vegetation_c(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NEO_div_vegetation_c_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NEO_modis_ndvi(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NEO_modis_ndvi_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NMCRef(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NMCRef_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NMCVel(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NMCVel_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NOC_ndvi(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NOC_ndvi_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def OceanLakeLandSnow(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def OceanLakeLandSnow_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_Gallet13(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_Gallet13_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_Lindaa06(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_Lindaa06_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_Lindaa07(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_Lindaa07_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_bhw3_22(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_bhw3_22_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_es_landscape_79(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_es_landscape_79_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_feb_sunrise(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_feb_sunrise_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_foggy_sunrise(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_foggy_sunrise_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_fs2006(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def SVG_fs2006_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def StepSeq25(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def StepSeq25_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def UKM_hadcrut(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def UKM_hadcrut_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def ViBlGrWhYeOrRe(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def ViBlGrWhYeOrRe_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhBlGrYeRe(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhBlGrYeRe_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhBlReWh(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhBlReWh_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhViBlGrYeOrRe(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhViBlGrYeOrRe_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhViBlGrYeOrReWh(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhViBlGrYeOrReWh_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhiteBlue(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhiteBlue_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhiteBlueGreenYellowRed(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhiteBlueGreenYellowRed_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhiteGreen(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhiteGreen_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhiteYellowOrangeRed(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def WhiteYellowOrangeRed_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def amwg(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def amwg_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def amwg256(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def amwg256_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def amwg_blueyellowred(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def amwg_blueyellowred_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cb_9step(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cb_9step_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cb_rainbow(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cb_rainbow_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cb_rainbow_inv(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cb_rainbow_inv_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def circular_0(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def circular_0_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def circular_1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def circular_1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def circular_2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def circular_2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cividis(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cividis_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_algae(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_algae_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_amp(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_amp_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_balance(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_balance_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_curl(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_curl_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_deep(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_deep_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_delta(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_delta_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_dense(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_dense_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_gray(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_gray_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_haline(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_haline_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_ice(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_ice_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_matter(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_matter_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_oxy(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_oxy_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_phase(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_phase_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_solar(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_solar_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_speed(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_speed_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_tempo(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_tempo_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_thermal(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_thermal_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_turbid(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmocean_turbid_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmp_b2r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmp_b2r_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmp_flux(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmp_flux_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmp_haxby(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmp_haxby_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cosam(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cosam_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cosam12(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cosam12_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cyclic(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cyclic_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def default(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def default_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def detail(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def detail_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def drought_severity(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def drought_severity_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def example(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def example_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def extrema(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def extrema_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def grads_default(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def grads_default_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def grads_rainbow(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def grads_rainbow_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def gscyclic(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def gscyclic_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def gsdtol(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def gsdtol_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def gsltod(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def gsltod_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def gui_default(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def gui_default_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def helix(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def helix_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def helix1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def helix1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def hlu_default(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def hlu_default_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def hotcold_18lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def hotcold_18lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def hotcolr_19lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def hotcolr_19lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def hotres(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def hotres_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def lithology(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def lithology_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def matlab_hot(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def matlab_hot_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def matlab_hsv(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def matlab_hsv_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def matlab_jet(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def matlab_jet_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def matlab_lines(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def matlab_lines_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def mch_default(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def mch_default_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def ncl_default(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def ncl_default_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def ncview_default(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def ncview_default_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def nice_gfdl(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def nice_gfdl_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def nrl_sirkes(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def nrl_sirkes_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def nrl_sirkes_nowhite(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def nrl_sirkes_nowhite_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def perc2_9lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def perc2_9lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def percent_11lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def percent_11lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def posneg_1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def posneg_1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def posneg_2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def posneg_2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def prcp_1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def prcp_1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def prcp_2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def prcp_2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def prcp_3(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def prcp_3_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip2_15lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip2_15lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip2_17lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip2_17lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip3_16lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip3_16lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip4_11lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip4_11lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip4_diff_19lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip4_diff_19lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip_11lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip_11lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip_diff_12lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip_diff_12lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip_diff_1lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def precip_diff_1lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def psgcap(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def psgcap_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def radar(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def radar_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def radar_1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def radar_1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_rainbow_gray(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_rainbow_gray_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_rainbow_white_gray(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_rainbow_white_gray_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_rainbow_white(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_rainbow_white_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def rainbow(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def rainbow_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def rh_19lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def rh_19lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def seaice_1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def seaice_1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def seaice_2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def seaice_2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def so4_21(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def so4_21_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def so4_23(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def so4_23_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def spread_15lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def spread_15lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def srip_reanalysis(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def srip_reanalysis_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def sunshine_9lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def sunshine_9lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def sunshine_diff_12lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def sunshine_diff_12lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def t2m_29lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def t2m_29lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def tbrAvg1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def tbrAvg1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def tbrStd1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def tbrStd1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def tbrVar1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def tbrVar1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_tbr_240_300(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_tbr_240_300_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_tbr_stdev_0_30(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_tbr_stdev_0_30_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_tbr_var_0_500(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_tbr_var_0_500_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def temp1(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def temp1_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def temp_19lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def temp_19lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def temp_diff_18lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def temp_diff_18lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def temp_diff_1lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def temp_diff_1lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def testcmap(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def testcmap_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def thelix(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def thelix_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def topo_15lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def topo_15lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def uniform(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def uniform_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def vegetation_ClarkU(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def vegetation_ClarkU_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def vegetation_modis(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def vegetation_modis_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def wgne15(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def wgne15_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_wh_bl_gr_ye_re(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def cmaps_wh_bl_gr_ye_re_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def wind_17lev(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def wind_17lev_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def wxpEnIR(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def wxpEnIR_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def Carbone42(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def Carbone42_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NMCRef(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NMCRef_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NMCVel2(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NMCVel2_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NWSRef(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NWSRef_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NWSSPW(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NWSSPW_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NWSVel(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def NWSVel_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def TopoGray(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def TopoGray_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def TwoClass(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def TwoClass_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def mask(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    
    @property
    def mask_r(self): # -> matplotlib.colors.Colormap | cmaps.colormap.Colormap:
        ...
    


