"""
This type stub file was generated by pyright.
"""

from matplotlib import colors

class Colormap(colors.ListedColormap):
    def __init__(self, c, name=..., n=...) -> None:
        '''Initialization'''
        ...
    
    def __getitem__(self, item): # -> Colormap:
        ...
    
    def __add__(self, o): # -> Colormap:
        ...
    
    def interp(self, lutsize: int): # -> Colormap:
        '''
        different from resampled of the new version of matplotlib (we interp colors here)
        '''
        ...
    
    def to_seg(self, N=...): # -> LinearSegmentedColormap:
        ...
    
    def show(self): # -> None:
        ...
    


