[project]
name = "fcstverif"
version = "1.2.0"
description = "Forecast Verification Framework"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Gaeun Kim", email = "gaeun.kim0921@gmail.com" }
]
# 최소 의존성 나열 (필요시 버전 범위 추가 권장)
dependencies = [
  "xarray",
  "numpy",
  "pandas",
  "matplotlib",
  "pygrib",
  "xskillscore",
  "netCDF4",
  "scipy"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]