# pyproject.toml

[project]
name = "fcstverif"
version = "1.2.1"
description = "Forecast Verification Framework"
authors = [{name="Gaeun Kim", email="gkim@apcc21.org"}]
dependencies = ["xarray", "numpy", "pandas", "matplotlib", "pygrib"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["fcstverif"]
